apiVersion: v1
kind: Service
metadata:
  name: {{ include "atlas-forge.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: atlas-forge
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
