apiVersion: v1
kind: Service
metadata:
  name: {{ include "news-engine.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: news-engine
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
