replicaCount: 2
image:
  repository: ghcr.io/filadelfal/user-management
  digest: "sha256:0c89b91113eeaf4bbfb567fd6753f2559c327dc283bbbbae0781225fec707c55"
  pullPolicy: IfNotPresent
service:
  port: 3002
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
