package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"time"

	"github.com/redis/go-redis/v9"
)

const operationsRetention=365*24*time.Hour
type redisPaperOperationsStore struct{client *redis.Client;retention time.Duration}
func(s redisPaperOperationsStore)AcquireReconciliation(ctx context.Context,owner string,ttl time.Duration)(func(context.Context)error,error){key:="trading-engine:paper-operations:reconciliation-lock";ok,err:=s.client.SetNX(ctx,key,owner,ttl).Result();if err!=nil{return nil,err};if !ok{return nil,errors.New("reconciliation lock contention")};return func(releaseCtx context.Context)error{script:=redis.NewScript(`if redis.call("GET",KEYS[1]) == ARGV[1] then return redis.call("DEL",KEYS[1]) else return 0 end`);return script.Run(releaseCtx,s.client,[]string{key},owner).Err()},nil}
func(s redisPaperOperationsStore)eventKey(id string)string{return "trading-engine:paper-ledger-event:"+id}
func(s redisPaperOperationsStore)Append(ctx context.Context,e paperLedgerEvent)(result paperLedgerEvent,created bool,err error){key:=s.eventKey(e.EventID);err=s.client.Watch(ctx,func(tx *redis.Tx)error{old,readErr:=tx.Get(ctx,key).Bytes();if readErr==nil{if json.Unmarshal(old,&result)!=nil{return errors.New("invalid ledger record")};if result.LedgerFingerprint!=e.LedgerFingerprint{return errors.New("ledger idempotency conflict")};return nil};if !errors.Is(readErr,redis.Nil){return readErr};last,readErr:=tx.LIndex(ctx,"trading-engine:paper-ledger",-1).Bytes();expected:="GENESIS";if readErr==nil{var prior paperLedgerEvent;if json.Unmarshal(last,&prior)!=nil{return errors.New("invalid ledger chain")};expected=prior.LedgerFingerprint}else if !errors.Is(readErr,redis.Nil){return readErr};if e.PreviousStateFingerprint!=expected||!validLedgerEvent(e){return errors.New("invalid ledger event")};payload,_:=json.Marshal(e);_,pipeErr:=tx.TxPipelined(ctx,func(pipe redis.Pipeliner)error{pipe.Set(ctx,key,payload,s.retention);pipe.RPush(ctx,"trading-engine:paper-ledger",payload);pipe.Expire(ctx,"trading-engine:paper-ledger",s.retention);return nil});if pipeErr==nil{result=e;created=true};return pipeErr},key,"trading-engine:paper-ledger");return}
func(s redisPaperOperationsStore)Ledger(ctx context.Context,offset,limit int)([]paperLedgerEvent,error){if offset<0||limit<1||limit>100{return nil,errors.New("invalid pagination")};items,err:=s.client.LRange(ctx,"trading-engine:paper-ledger",int64(offset),int64(offset+limit-1)).Result();if err!=nil{return nil,err};out:=make([]paperLedgerEvent,0,len(items));for _,item:=range items{var e paperLedgerEvent;if json.Unmarshal([]byte(item),&e)!=nil{return nil,errors.New("invalid ledger record")};out=append(out,e)};return out,nil}
func(s redisPaperOperationsStore)SaveRun(ctx context.Context,r reconciliationRun,fs []reconciliationFinding)error{payload,_:=json.Marshal(r);created,err:=s.client.SetNX(ctx,"trading-engine:reconciliation-run:"+r.RunID,payload,s.retention).Result();if err!=nil{return err};if !created{old,err:=s.client.Get(ctx,"trading-engine:reconciliation-run:"+r.RunID).Bytes();if err!=nil{return err};var prior reconciliationRun;if json.Unmarshal(old,&prior)!=nil||fingerprint(prior)!=fingerprint(r){return errors.New("run conflict")};return nil};pipe:=s.client.Pipeline();pipe.ZAdd(ctx,"trading-engine:reconciliation-runs",redis.Z{Score:float64(r.StartedAt.UnixNano()),Member:r.RunID});for _,f:=range fs{b,_:=json.Marshal(f);pipe.Set(ctx,"trading-engine:reconciliation-finding:"+f.FindingID,b,s.retention);pipe.ZAdd(ctx,"trading-engine:reconciliation-findings",redis.Z{Score:float64(f.DetectedAt.UnixNano()),Member:f.FindingID});pipe.ZAdd(ctx,"trading-engine:reconciliation-active",redis.Z{Score:float64(f.DetectedAt.UnixNano()),Member:f.FindingID})};_,err=pipe.Exec(ctx);return err}
func(s redisPaperOperationsStore)Runs(ctx context.Context,n int)([]reconciliationRun,error){if n<1||n>100{return nil,errors.New("invalid limit")};ids,err:=s.client.ZRevRange(ctx,"trading-engine:reconciliation-runs",0,int64(n-1)).Result();if err!=nil{return nil,err};out:=[]reconciliationRun{};for _,id:=range ids{b,err:=s.client.Get(ctx,"trading-engine:reconciliation-run:"+id).Bytes();if err!=nil{return nil,err};var r reconciliationRun;if json.Unmarshal(b,&r)!=nil{return nil,errors.New("invalid run")};out=append(out,r)};return out,nil}
func(s redisPaperOperationsStore)Findings(ctx context.Context,active bool,n int)([]reconciliationFinding,error){if n<1||n>100{return nil,errors.New("invalid limit")};key:="trading-engine:reconciliation-findings";if active{key="trading-engine:reconciliation-active"};ids,err:=s.client.ZRange(ctx,key,0,int64(n-1)).Result();if err!=nil{return nil,err};out:=[]reconciliationFinding{};for _,id:=range ids{b,err:=s.client.Get(ctx,"trading-engine:reconciliation-finding:"+id).Bytes();if err!=nil{return nil,err};var f reconciliationFinding;if json.Unmarshal(b,&f)!=nil{return nil,errors.New("invalid finding")};out=append(out,f)};return out,nil}
func(s redisPaperOperationsStore)Resolve(ctx context.Context,id string,at time.Time)error{key:="trading-engine:reconciliation-finding:"+id;b,err:=s.client.Get(ctx,key).Bytes();if err!=nil{return err};var f reconciliationFinding;if json.Unmarshal(b,&f)!=nil{return errors.New("invalid finding")};if f.ResolvedAt==nil{v:=at.UTC();f.ResolvedAt=&v;b,_=json.Marshal(f);pipe:=s.client.Pipeline();pipe.Set(ctx,key,b,s.retention);pipe.ZRem(ctx,"trading-engine:reconciliation-active",id);_,err=pipe.Exec(ctx)};return err}
func(s redisPaperOperationsStore)SaveRollup(ctx context.Context,r dailyPaperRollup)error{key:="trading-engine:paper-rollup:"+r.Date;b,_:=json.Marshal(r);return s.client.Set(ctx,key,b,s.retention).Err()}
func(s redisPaperOperationsStore)Rollup(ctx context.Context,date string)(dailyPaperRollup,error){b,err:=s.client.Get(ctx,"trading-engine:paper-rollup:"+date).Bytes();if err!=nil{return dailyPaperRollup{},err};var r dailyPaperRollup;err=json.Unmarshal(b,&r);return r,err}

func boundedIndex(ctx context.Context,client *redis.Client,key string)([]string,error){items,err:=client.ZRange(ctx,key,0,1000).Result();if err!=nil{return nil,err};if len(items)>1000{return nil,fmt.Errorf("bounded index exceeded: %s",key)};return items,nil}
func collectRedisOperationsEvidence(ctx context.Context,app *application,ops paperOperationsStore,startingEquity float64)(operationsEvidence,error){e:=operationsEvidence{Journals:map[string][]paperJournalEvent{},Risk:operationsRiskState{StartingEquity:startingEquity,PairExposure:map[string]bool{},TradingEnabled:true}};requestIDs,err:=boundedIndex(ctx,app.cache,"trading-engine:paper-order-index");if err!=nil{return e,err};for _,id:=range requestIDs{o,err:=app.paperStore.Get(ctx,id);if err!=nil{return e,err};e.Orders=append(e.Orders,o)};orderIDs,err:=boundedIndex(ctx,app.cache,"trading-engine:paper-position-index");if err!=nil{return e,err};for _,id:=range orderIDs{var p paperPosition;if err:=decodeRedisPosition(ctx,app.cache,"trading-engine:paper-position:"+id,&p);err!=nil{return e,err};e.Positions=append(e.Positions,p);journal,err:=app.lifecycleStore.Journal(ctx,id);if err!=nil{return e,err};e.Journals[id]=journal};runtimeStore:=redisRuntimeStore{client:app.cache,prefix:"trading-engine:paper-runtime:"};e.Cycles,err=runtimeStore.Recent(ctx,100);if err!=nil{return e,err};for offset:=0;offset<1000;offset+=100{page,err:=ops.Ledger(ctx,offset,100);if err!=nil{return e,err};e.Ledger=append(e.Ledger,page...);if len(page)<100{break};if offset==900&&len(page)==100{return e,errors.New("ledger reconciliation bound exceeded")}};realized,unrealized:=0.0,0.0;open:=0;for _,p:=range e.Positions{if p.Status=="OPEN"{open++;unrealized+=p.UnrealizedPnL;e.Risk.PairExposure[p.Pair]=true}else{realized+=p.RealizedPnL}};e.Risk.OpenPositionCount=open;e.Risk.DailyRealizedPnL=realized;e.Risk.CurrentEquity=startingEquity+realized+unrealized;e.Risk.PeakEquity=startingEquity;if e.Risk.CurrentEquity>e.Risk.PeakEquity{e.Risk.PeakEquity=e.Risk.CurrentEquity};if startingEquity>0&&realized<0{e.Risk.DailyLossPercent=-realized/startingEquity*100};if e.Risk.PeakEquity>0{e.Risk.DrawdownPercent=(e.Risk.PeakEquity-e.Risk.CurrentEquity)/e.Risk.PeakEquity*100};for _,pair:=range []string{"EURUSD","GBPUSD","USDJPY"}{exists,err:=app.cache.Exists(ctx,"trading-engine:paper-automation-open-pair:"+pair).Result();if err!=nil{return e,err};if exists>0{e.Risk.PairExposure[pair]=true}};sort.Slice(e.Orders,func(i,j int)bool{return e.Orders[i].CreatedAt.Before(e.Orders[j].CreatedAt)});sort.Slice(e.Positions,func(i,j int)bool{return e.Positions[i].OpenedAt.Before(e.Positions[j].OpenedAt)});return e,nil}
