apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "admin-panel.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: admin-panel
  template:
    metadata:
      labels:
        app.kubernetes.io/name: admin-panel
    spec:
      containers:
        - name: admin-panel
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: PORT
              value: "{{ .Values.service.port }}"
          resources:
{{ toYaml .Values.resources | nindent 12 }}
